# duration is self-explanatory
duration: 3

# durationBetweenWorlds needs to be higher
# because it gets triggered onTeleport and not "onArrival"
# so the player needs a bit of time to load the world
# on any movement (even an entity hit)
# the effect goes down to 3 anyway
durationBetweenWorlds: 10