name: BackInvulnerability
main: me.atomiz.backinvulnerability.Main
version: 1.0
author: Atomiz
api-version: 1.17
commands:
  backinvulnerability:
    description: Main command for BackInvulnerability
    aliases: bi
    usage: bi reload
    permission: backinvulnerability.reload
    permission-message: You have no permission to execute this command.
permissions:
  backInvulnerability.reload:
    default: op
    description: Allows the reload command to be executed.